cc_binary(
	name = 'demo',
	srcs = ['demo.cc'],
	deps = [
		'//:workflow-polaris',
		'@com_github_sogou_workflow//:http',
		'@com_github_sogou_workflow//:upstream',
		'@com_github_sogou_workflow//:workflow_hdrs',
	],
)
